### ISSUE TITLE
Переименовать Pages в UI

### ISSUE THREAD

**Issue by FEW172** [FEW172/EDSManager#5]
Предлагаю рассмотреть переименование каталога Pages в UI (Интерфейс пользователя)

**Comment by AlexS-84** [comment]
Согласовано

**Comment by FEW172** [comment]
> 
> 
> Предлагаю рассмотреть переименование каталога Pages в UI (Интерфейс пользователя)
> 
> Согласовано

**Comment by Vershanskijda** [comment]
Согласовано
